---
- hosts: all
  tasks:
  - user: name=corey shell=/bin/bash home=/home/corey createhome=yes
  - file: path=/home/corey/.ssh state=directory owner=corey mode=0700
  - get_url: url=https://github.com/Dennovin.keys dest=/home/corey/.ssh/authorized_keys validate_certs=no
  - file: path=/home/corey/.ssh/authorized_keys owner=corey group=corey mode=0600
  - file: path=/data state=directory mode=0755
  - copy: src=app dest=/data/
  - apt: pkg={{ item }} state=present
    with_items:
    - tmux
    - python-pip
  - pip: requirements=/data/app/requirements.txt

- hosts: vagrant
  tasks:
  - lineinfile: state=present create=yes dest=/etc/apt/apt.conf.d/01proxy line='Acquire::http::Proxy "http://leviathan:3142";'
  - file: path=/etc/apt/apt.conf.d/01proxy owner=root group=root mode=0644
  - lineinfile: state=present dest=/etc/hosts line='192.168.121.1 leviathan'

- hosts: tex
  handlers:
  - name: unzip aniron font
    unarchive: src=/tmp/aniron.zip dest=/usr/local/share/fonts/ copy=no

  tasks:
  - apt: name={{ item }} state=present
    with_items:
    - fontconfig
    - texlive-xetex
    - texlive-latex-recommended
    - texlive-latex-extra
    - unzip
  - get_url: dest=/usr/local/share/fonts/{{ item }} url=https://github.com/google/fonts/blob/master/ofl/ptsans/{{ item }}?raw=true
    with_items:
    - PT_Sans-Web-Regular.ttf
    - PT_Sans-Web-Bold.ttf
    - PT_Sans-Web-Italic.ttf
    - PT_Sans-Web-BoldItalic.ttf
  - get_url: dest=/tmp/aniron.zip url=http://dl.1001fonts.com/aniron.zip
    notify: unzip aniron font
  - copy: src=tex dest=/data/



