---
- hosts: all
  become: yes
  vars_files:
  - passwords.yaml
  tasks:
  - name: update apt cache
    apt: update_cache=yes cache_valid_time=86400

  - name: create app group
    group: name=zyxxid state=present gid=2001

  - name: create app user
    user: name=zyxxid uid=2001 groups=zyxxid append=yes

  - name: install packages for all systems
    apt: pkg={{ item }} state=present
    with_items:
    - tmux
    - git

  - name: create required directories
    file: path={{ item }} state=directory owner=zyxxid group=zyxxid mode=0755
    with_items:
    - /data/etc
    - /data/logs

  - name: create config file
    template: src=templates/zyxxid.yaml.j2 dest=/data/etc/zyxxid.yaml owner=zyxxid mode=0644


- hosts: tex:web
  tasks:
  - name: install Python and required libraries
    apt: name={{ item }} state=present
    with_items:
    - python3-pip
    - python-virtualenv
    - python-dev
    - libffi-dev
    - libssl-dev
    - libyaml-0-2
    - libmemcached-dev

  - name: synchronize app folder
    copy: src=app dest=/data/ force=yes owner=zyxxid group=zyxxid

  - name: install app into virtual environment
    pip: name="file:///data/app" virtualenv=/data/venv virtualenv_python=python3.4
    become: yes
    become_user: zyxxid


- hosts: tex
  handlers:
  - name: unzip Aniron font
    unarchive: src=/tmp/aniron.zip dest=/usr/local/share/fonts/ copy=no

  tasks:
  - name: install LaTeX and celery requirements
    apt: name={{ item }} state=present
    with_items:
    - celeryd
    - fontconfig
    - latex-xcolor
    - texlive-generic-recommended
    - texlive-latex-extra
    - texlive-latex-recommended
    - texlive-xetex
    - unzip

  - name: download PT Sans fonts
    get_url: dest=/usr/local/share/fonts/{{ item }} url=https://github.com/google/fonts/blob/master/ofl/ptsans/{{ item }}?raw=true
    with_items:
    - PT_Sans-Web-Regular.ttf
    - PT_Sans-Web-Bold.ttf
    - PT_Sans-Web-Italic.ttf
    - PT_Sans-Web-BoldItalic.ttf

  - name: download Aniron font
    get_url: dest=/tmp/aniron.zip url=http://dl.1001fonts.com/aniron.zip
    notify: unzip Aniron font

  - name: synchronize tex folder
    copy: src=tex dest=/data/ force=yes owner=zyxxid group=zyxxid

  - name: create output directory
    file: path=/data/output state=directory owner=zyxxid group=zyxxid

  - name: create ramdisk
    mount: name=/data/output src=tmpfs fstype=tmpfs opts="size=128M" state=mounted

  - name: copy files to output directory
    copy: src=tex/{{ item }} dest=/data/output/ force=yes owner=zyxxid group=zyxxid
    with_items:
    - charactersheet.cls

  - name: set up celeryd from template
    template: src=templates/celeryd.j2 dest=/etc/default/celeryd owner=root mode=0644

  - name: start and enable celeryd
    service: name=celeryd enabled=yes state=started


- hosts: web
  handlers:
  - name: restart nginx
    service: name=nginx state=restarted

  - name: restart uWSGI
    service: name=uwsgi state=restarted

  tasks:
  - name: install nginx
    apt: name={{ item }} state=present
    with_items:
    - nginx

  - name: set up nginx from template
    template: src=templates/nginx.conf.j2 dest=/etc/nginx/sites-available/zyxxid owner=root mode=0644
    notify: restart nginx

  - name: enable nginx site
    file: dest=/etc/nginx/sites-enabled/zyxxid src=/etc/nginx/sites-available/zyxxid state=link

  - name: disable default nginx site
    file: dest=/etc/nginx/sites-enabled/default state=absent

  - name: remove default nginx files
    file: dest=/etc/nginx/conf.d/{{ item }} state=absent
    with_items:
    - default.conf
    - virtual.conf
    - ssl.conf
    notify: restart nginx

  - name: add nginx user to app group
    user: name=www-data groups=zyxxid append=yes

  - name: set up uWSGI from template
    template: src=templates/uwsgi.ini.j2 dest=/data/etc/uwsgi.ini
    notify: restart uWSGI

  - name: set up uWSGI service from template
    template: src=templates/uwsgi.conf.j2 dest=/etc/init/uwsgi.conf
    notify: restart uWSGI

  - name: start and enable uWSGI
    service: name=uwsgi enabled=yes state=started

  - name: synchronize static web files
    synchronize: src=web/ dest=/data/www owner=no

  - name: set owner of static web files
    file: path=/data/www owner=www-data state=directory recurse=yes

  - name: check out grimoire
    git: repo=https://github.com/ephe/grimoire.git dest=/data/grimoire


- hosts: db
  vars_files:
  - passwords.yaml
  handlers:
  - name: restart Riak
    service: name=riak state=restarted

  - name: restart memcached
    service: name=memcached state=restarted

  tasks:
  - name: install database server packages
    apt: name={{ item }} state=present
    with_items:
    - rabbitmq-server
    - memcached

  - name: set up Riak from template
    template: src=templates/riak.conf.j2 dest=/etc/riak/riak.conf owner=root mode=0644
    notify: restart Riak

  - name: download Riak
    get_url: url=http://s3.amazonaws.com/downloads.basho.com/riak/2.1/2.1.4/ubuntu/trusty/riak_2.1.4-1_amd64.deb dest=/tmp/riak_2.1.4-1_amd64.deb

  - name: install Riak
    apt: deb=/tmp/riak_2.1.4-1_amd64.deb state=present

  - name: start and enable Riak
    service: name=riak enabled=yes state=started

  - name: add RabbitMQ user
    rabbitmq_user: user=zyxxid password={{ rabbitmq_password }} vhost=/ configure_priv=.* read_priv=.* write_priv=.* state=present

  - name: set up memcached from template
    template: src=templates/memcached.conf.j2 dest=/etc/memcached.conf owner=root mode=0644
    notify: restart memcached

  - name: start and enable memcached
    service: name=memcached enabled=yes state=started
