---
- hosts: tex:web
  become: yes
  tasks:
  - name: install Python and required libraries
    apt: name={{ item }} state=present
    with_items:
    - python3-pip
    - python-virtualenv
    - python-dev
    - libffi-dev
    - libssl-dev
    - libyaml-0-2

  - name: synchronize app folder
    become: no
    synchronize:
      src: ../app
      dest: /data/
      rsync_opts:
        - "--exclude=.git"

  - name: set permissions on app folder
    file: path=/data/app state=directory owner=zyxxid group=zyxxid recurse=yes

  - name: install app into virtual environment
    pip: name="file:///data/app" virtualenv=/data/venv virtualenv_python=python3.5
    become: yes
    become_user: zyxxid

  - name: copy template directory
    become: no
    synchronize:
      src: ../templates
      dest: /data/
      rsync_opts:
        - "--exclude=.git"
